### ISSUE TITLE
Calling twice dynamo.put.promise

### ISSUE THREAD

**Issue by LeoFuna** [sramalho94/cdk-first-ts#12]
https://github.com/sramalho94/cdk-first-ts/blob/509970fb32ddc34262b7617c3808b465c0cbd103/functions/function.ts#L149-L158

Im not sure why we need to call twice `dynamo.put().promise`, will we not create a duplicated data?

Why not just call one time and get the return of this call to use as the return of `saveItem` function?

**Comment by sramalho94** [comment]
haha great catch, not too sure what I was thinking there. The dynamodb put method doesn't return anything: `DynamoDB.DocumentClient.PutItemInput, callback?: ((err: AWS.AWSError, data: DynamoDB.DocumentClient.PutItemOutput) => void)` so I'll just return `item`
