### ISSUE TITLE
Line 7, 13, 30, 56

### ISSUE THREAD

**Issue by LeoFuna** [sramalho94/cdk-first-ts#5]
https://github.com/sramalho94/cdk-first-ts/blob/509970fb32ddc34262b7617c3808b465c0cbd103/functions/function.ts#L13

I really like those comments on your own repo for studing/reviewing purposes.

But when we push this to our repo, i think they are not really necessary because your interfaces/var names are very self-explained.

Would be good to comment only really necessary things.

**Comment by sramalho94** [comment]
sounds good!
