### ISSUE TITLE
Enhance legibility using Early Return

### ISSUE THREAD

**Issue by LeoFuna** [sramalho94/cdk-first-ts#6]
https://github.com/sramalho94/cdk-first-ts/blob/509970fb32ddc34262b7617c3808b465c0cbd103/functions/function.ts#L38-L47

Thats is a suggestion, your code is completely right :heavy_check_mark: 

When we talk about legibility, those if/else if statements are not so good.
We can use a really good approach which is [early return](https://medium.com/swlh/return-early-pattern-3d18a41bba8).

[Here](https://gist.github.com/LeoFuna/08cdaf14b31fe946db122b3ff963290e) a gist that i created using the same code with early return pattern.

As i said before, its a sugestion trying to make this code more legible.

**Comment by sramalho94** [comment]
great suggestion, implemented!
