### ISSUE TITLE
Standardization about lambda response

### ISSUE THREAD

**Issue by LeoFuna** [sramalho94/cdk-first-ts#7]
https://github.com/sramalho94/cdk-first-ts/blob/509970fb32ddc34262b7617c3808b465c0cbd103/functions/function.ts#L45

Do you see that we are not having a standardization in that lambda function about the returned data?

Here we are returning a body with a `string` message but in some other cases we are returning `{  message: "some msg" }`.

Can we make everything as `{  }`? To follow some kind of pattern

**Comment by sramalho94** [comment]
fixed! it's consistent now, I used the `{  message: "some msg" }` format because most response bodies aligned with that format already
